name: Deploy MAZOL Node
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name: Install Java
        run: sudo apt update && sudo apt install -y openjdk-11-jdk
      - name: Download Hyperledger Besu
        run: |
          wget https://hyperledger.jfrog.io/artifactory/besu-binaries/besu/23.4.1/besu-23.4.1.zip
          unzip besu-23.4.1.zip
      - name: Start Node
        run: |
          ./besu-23.4.1/bin/besu \
          --genesis-file=genesis.json \
          --network-id=2024 \
          --rpc-http-enabled \
          --host-allowlist="*"
